
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const LOGDB = 'LOGDB'
export const REDIS_CONNECTION = 'REDIS_CONNECTION'

export const DATABASE_CONNECTION = 'DATABASE_CONNECTION'
export const TESTING_REPOSITORY='TESTING_REPOSITORY'

export const USER_REPOSITORY = 'USER_REPOSITORY';

export const SIGNAL_REPOSITORY = 'SIGNAL_REPOSITORY';
export const SIGNAL_TARGET_REPOSITORY = 'SIGNAL_TARGET_REPOSITORY';
export const COINTYPE_REPOSITORY = 'COINTYPE_REPOSITORY';
export const SIGNALVIEW_REPOSITORY = 'SIGNALVIEW_REPOSITORY';
export const SIGNALUNLOKMAP_REPOSITORY = 'SIGNALUNLOKMAP_REPOSITORY';

export const CAMPAIGN_REPOSITORY = 'CAMPAIGN_REPOSITORY';