
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const LOGDB = 'LOGDB'
export const REDIS_CONNECTION = 'REDIS_CONNECTION'

export const DATABASE_CONNECTION = 'DATABASE_CONNECTION'
export const TESTING_REPOSITORY='TESTING_REPOSITORY'

export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_TEMP_REPOSITORY = 'USER_TEMP_REPOSITORY';
export const USER_DEVICE_REPOSITORY = 'USER_DEVICE_REPOSITORY';
export const PASSWORD_CONFIG_REPOSITORY = 'PASSWORD_CONFIG_REPOSITORY';
export const PROTOCOL_REPOSITORY = 'PROTOCOL_REPOSITORY';
export const COUNTRIES_REPOSITORY = 'COUNTRIES_REPOSITORY';
export const HEROLISTVIEW_REPOSITORY = 'HEROLISTVIEW_REPOSITORY';
export const FOLLOWINGHEROLISTVIEW_REPOSITORY = 'FOLLOWINGHEROLISTVIEW_REPOSITORY';
export const SUBSCRIBEHEROLISTVIEW_REPOSITORY = 'SUBSCRIBEHEROLISTVIEW_REPOSITORY';
export const FOLLOWERMAP_REPOSITORY = 'FOLLOWERMAP_REPOSITORY';
export const SUBSCRIBERMAP_REPOSITORY = 'SUBSCRIBERMAP_REPOSITORY';

export const SIGNAL_REPOSITORY = 'SIGNAL_REPOSITORY';
export const SIGNAL_TARGET_REPOSITORY = 'SIGNAL_TARGET_REPOSITORY';
export const COINTYPE_REPOSITORY = 'COINTYPE_REPOSITORY';
export const SIGNALVIEW_REPOSITORY = 'SIGNALVIEW_REPOSITORY';
export const SIGNALUNLOKMAP_REPOSITORY = 'SIGNALUNLOKMAP_REPOSITORY';

export const CAMPAIGN_REPOSITORY = 'CAMPAIGN_REPOSITORY';